import Auth.http

###
run #Auth and get token

### GET request to example server
# @no-auto-encoding
GET {{baseUrl}}/v2/absences
    ?persons=[190]
    &beginDate=2024-01-01&endDate=2024-12-31
    &usePersonnelNumbers=true
Authorization: Bearer {{token}}
###